/**
 * Nuri Audio Factory — Orchestrator
 * Full pipeline: research topic → compile sources → NotebookLM → audio brief
 *
 * Usage (from Node):
 *   const { runAudioFactory } = require('./plugins/audio-factory');
 *   await runAudioFactory({ topic: 'AI in healthcare', client: 'Acme Corp' });
 *
 * Usage (CLI):
 *   node index.js "AI in healthcare" "Acme Corp"
 *
 * ~/.openclaw/plugins/audio-factory/index.js
 */

'use strict';

const path = require('path');
const fs   = require('fs').promises;
const os   = require('os');

const { researchTopic }        = require('./research');
const { runNotebookLMPipeline } = require('./notebooklm');
const { sendTelegramAlert }    = require('../disaster-monitor');

// ─────────────────────────────────────────────────────────────────
// ANTHROPIC CLIENT
// ─────────────────────────────────────────────────────────────────

function getAnthropicClient() {
  try {
    const Anthropic = require('@anthropic-ai/sdk');
    return new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
  } catch {
    throw new Error('Install @anthropic-ai/sdk: npm install @anthropic-ai/sdk');
  }
}

// ─────────────────────────────────────────────────────────────────
// HELPERS
// ─────────────────────────────────────────────────────────────────

function resolveOutputDir(client, topic) {
  const base    = (process.env.AUDIO_PROJECTS_DIR || '~/.openclaw/audio-projects')
    .replace('~', os.homedir());
  const slug    = [client, topic]
    .join('-')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .slice(0, 60);
  return path.join(base, slug);
}

async function notifyTelegram(client, topic, notebookUrl, audioUrl) {
  const msg =
    `🎙️ *Audio Brief Ready*\n\n` +
    `*Client:* ${client}\n` +
    `*Topic:* ${topic}\n\n` +
    `📓 Notebook: ${notebookUrl}\n` +
    (audioUrl !== notebookUrl ? `🔊 Audio: ${audioUrl}\n` : '') +
    `\n_Generated by Nuri Audio Factory_`;
  await sendTelegramAlert(msg).catch(e =>
    console.warn('[audio-factory] Telegram alert failed:', e.message)
  );
}

// ─────────────────────────────────────────────────────────────────
// MAIN PIPELINE
// ─────────────────────────────────────────────────────────────────

/**
 * Run the full audio production pipeline.
 *
 * @param {Object}  opts
 * @param {string}  opts.topic      - Research topic / title
 * @param {string}  opts.client     - Client name (used for output directory and notebook title)
 * @param {boolean} [opts.headless] - Run browser headless (default true)
 * @param {boolean} [opts.skipNLM]  - Skip NotebookLM step (research only)
 * @returns {Promise<{sourcesPath, notebookUrl, audioUrl}>}
 */
async function runAudioFactory({ topic, client, headless = true, skipNLM = false }) {
  console.log(`\n🎙️  Nuri Audio Factory`);
  console.log(`   Topic:  ${topic}`);
  console.log(`   Client: ${client}\n`);

  const outputDir = resolveOutputDir(client, topic);
  await fs.mkdir(outputDir, { recursive: true });

  // ── Step 1: Research ──────────────────────────────────────────
  console.log('── Step 1: Researching topic...');
  const anthropic   = getAnthropicClient();
  const sourcesPath = await researchTopic(anthropic, topic, outputDir);
  console.log(`✅ Sources compiled → ${sourcesPath}\n`);

  if (skipNLM) {
    console.log('Skipping NotebookLM (--research-only flag set)');
    return { sourcesPath, notebookUrl: null, audioUrl: null };
  }

  // ── Step 2: NotebookLM ────────────────────────────────────────
  console.log('── Step 2: Uploading to NotebookLM...');
  const title        = `${client} — ${topic}`;
  const { notebookUrl, audioUrl } = await runNotebookLMPipeline({
    title,
    sourcesPath,
    headless,
  });
  console.log(`✅ Notebook: ${notebookUrl}`);
  console.log(`✅ Audio:    ${audioUrl}\n`);

  // ── Step 3: Persist manifest ──────────────────────────────────
  const manifest = { topic, client, sourcesPath, notebookUrl, audioUrl, createdAt: new Date().toISOString() };
  await fs.writeFile(
    path.join(outputDir, 'manifest.json'),
    JSON.stringify(manifest, null, 2),
    'utf8'
  );

  // ── Step 4: Telegram alert ────────────────────────────────────
  await notifyTelegram(client, topic, notebookUrl, audioUrl);

  console.log(`✅ Audio brief ready for ${client} on "${topic}"`);
  return manifest;
}

// ─────────────────────────────────────────────────────────────────
// CLI
// ─────────────────────────────────────────────────────────────────

if (require.main === module) {
  const [topic, client = 'Internal'] = process.argv.slice(2);

  if (!topic) {
    console.error('Usage: node index.js "<topic>" ["<client>"]');
    process.exit(1);
  }

  const skipNLM  = process.argv.includes('--research-only');
  const headless = !process.argv.includes('--show-browser');

  runAudioFactory({ topic, client, headless, skipNLM })
    .then(result => {
      console.log('\nManifest:', JSON.stringify(result, null, 2));
    })
    .catch(err => {
      console.error('\n[audio-factory] Failed:', err.message);
      process.exit(1);
    });
}

module.exports = { runAudioFactory };
